### ISSUE TITLE
Tracking Issue: Precompiles for Light Client

### ISSUE THREAD

**Issue by tchataigner** [lurk-lab/bls12_381#1]
Currently, we leverage the [zkvm](https://github.com/lurk-lab/bls12_381/tree/zkvm) or the [decompress](https://github.com/lurk-lab/bls12_381/tree/bls12381-g1-decompress) branch to leverage the pre-compiles in our light client implementation. I'm opening this issue to keep track of what is needed, what is available and what is to come.

## Usage in Light Client

For the Light Client usage we are leveraging the bls crate on two main structures: `PublicKey` and `Signature`. `PublicKey` are structure defined over `G1` while `Signature` are defined over `G2`. Those components have the following usage associated to them:
- [`PubllicKey`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L24-L27)
  - [`decompression`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L39-L48): Conversion from a compressed form (slice of 48 bytes) to its decompressed one.
  - [`aggregate`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L50-L64): Addition of `G1` decompressed points. In the future, we might also need substraction for optimization purposes.
- [`Signature`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L141-L143)
  -  [`decompression`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L170-L199): Conversion from a compressed form (slice of 96 bytes) to its decompressed one.
- [`signature_verification`](https://github.com/wormhole-foundation/example-zk-light-clients-internal/blob/feature/ratchet/aptos/core/src/crypto/sig.rs#L146-L159) : Verify an aggregated signature based on the aggregated public key, by leveraging the `pairing` mechanism.

## What's to be integrated

After some exchange with @wwared here is what we believe should be integrated in this crate for our purposes:

### Current status
**Already on the branch**

- [x] `add`, `sub`, `mul` of `Fp`
- [x] `add`, `sub`, `mul` of `Fp2`
- [x] Decompression of `G1` in the unchecked endpoint
- [x] `add` and `double` for `G1Affine` (used in `G1Affine::add_affine` only for now)

**To add**

- [ ] `add` for `G2Affine`

**To add in future work**

- [x] `Fp2` `sqrt` _(done, but not merged as a PR - might not get merged in favor of a G2 decompress precompile)_
- [x] `Fp` `sqrt` _(same as above)_
- [x] `Fp` `invert`
- [x] `Fp2` `invert`
- [ ] `double` for `G2Affine`
- [ ] `G2` `decompress` in the unchecked endpoint

**Comment by huitseeker** [comment]
### Initial PR
**Already on the branch**

- [x] `add`, `sub`, `mul` of `Fp`
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp.rs#L12
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp.rs#L13
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp.rs#L14
- [x] `add`, `sub`, `mul` of `Fp2`
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp2.rs#L11
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp2.rs#L12
    - https://github.com/lurk-lab/bls12_381/blob/46673a9dbf0edfb9cb100af45a19fd79a40fa29b/src/fp2.rs#L13
- [x] Decompression of `G1` in the unchecked endpoint
    - https://github.com/lurk-lab/bls12_381/blob/zkvm/src/g1.rs#L21

**Comment by storojs72** [comment]
G2Affine addition has been landed to `dev` of wp1 (https://github.com/wormhole-foundation/wp1/pull/160)

cc @tchataigner

**Comment by huitseeker** [comment]
All complete
